# from distutils.core import setup
from setuptools import setup

setup(
    name='ChronoRender',
    version='0.0.1',
    author='Aaron Bartholomew',
    author_email='abartholome2@wisc.edu',
    packages=['chronorender',
              'chronorender.attribute',
              'chronorender.camera',
              'chronorender.converter',
              'chronorender.data',
              'chronorender.data.dq',
              'chronorender.data.ds',
              'chronorender.data.nodes',
              'chronorender.dataprocess',
              'chronorender.datasource',
              'chronorender.datatarget',
              'chronorender.distributed',
              'chronorender.finder',
              'chronorender.geometry',
              'chronorender.light',
              'chronorender.lighting',
              'chronorender.math',
              'chronorender.metadata',
              'chronorender.movie',
              'chronorender.option',
              'chronorender.plugins',
              'chronorender.prog',
              'chronorender.renderer',
              'chronorender.renderobject',
              'chronorender.renderpass',
              'chronorender.renderpass.display',
              'chronorender.renderpass.hider',
              'chronorender.renderpass.settings',
              'chronorender.rendersettings',
              'chronorender.ri',
              'chronorender.rsl',
              'chronorender.scene',
              'chronorender.shader',
              'chronorender.simulation',
              'chronorender.thirdparty',
              'chronorender.thirdparty.yaml',
              'chronorender.visualizer'
        ],
    url='sbel.wisc.edu/Resources/Software/ChronoEngine/c_render',
    license='LICENSE.txt',
    description='RenderMan Rendering Service Package',
    long_description=open('README.txt').read(),
    )
