                      	
global proc addSphereRI()
{
// 1. Get the name of the object to which the 
string    $object = `rman ctxGetObject`;
  
// 1. Get the full name of an attribute defined in a .rman file
string     $attr = `rmanGetAttrName "asRad"`;

// 1. Get the full name of an attribute defined in a .rman file
float      $rad = `getAttr ($object + "." + $attr)`;
RiSphere($rad, -$rad, $rad, 360);
}
